#!/bin/bash

if [ "$1" = "--stop" ]; then
	docker-compose stop
	docker-sync stop
	exit 0
fi

SERVICE_NAME=$(cat .docker-compose-default-service | tr -d '[:space:]')
if [ -z "$SERVICE_NAME" ]; then
	echo "Configure default service name:"
	echo "echo service-name > .docker-compose-default-service"
	exit
fi

# Lets assume the default project name derivated from dir name
COMPOSE_CONTAINER_NAME=$(basename $(pwd) | tr -d '[-_]')_${SERVICE_NAME}_1

CONTAINER_RUNS_TEST=$(docker ps -q -f name=$COMPOSE_CONTAINER_NAME)
if [ -z "$CONTAINER_RUNS_TEST" ]; then
	echo "Container $COMPOSE_CONTAINER_NAME not running... Starting docker-sync and docker-compose"

	# start sync always - it just fails if it is already running
	docker-sync start -d

	# start docker-compose if it is not running
	if [ -f docker-compose.override.yml ]; then
		docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
	else
		docker-compose up -d
	fi
fi

# Run it using docker instead of docker-compose as it is much faster to bootstrap
docker exec -it $COMPOSE_CONTAINER_NAME $@
